### ISSUE TITLE
Can't get/list brokers.eventing.knative.dev

### ISSUE THREAD

**Issue by benmoss** [vmware-tanzu/sources-for-knative#220]
Tried to deploy this VSphereSource:
```yaml
apiVersion: sources.tanzu.vmware.com/v1alpha1
kind: VSphereSource
metadata:
  name: vcsimsource
spec:
 sink:
   ref:
    apiVersion: eventing.knative.dev/v1
    kind: Broker
    name: potato
    namespace: default
 address: https://vcsim.default.svc.cluster.local
 skipTLSVerify: true
 secretRef:
   name: vsphere-credentials
```

and saw the error `brokers.eventing.knative.dev "Lister" not found` in the events of the object.

It seems like this controller should have a binding to the [addressable-resolver](https://github.com/knative/eventing/blob/c820f4239730dacf5b2e0e5eed67a496bdc9b424/config/core/roles/addressable-resolvers-clusterrole.yaml) ClusterRole so that it can resolve any ref that's participating in the `addressable` duck type.

Wasn't sure if this means that the podspecable binding that we have today is in error or if we need both of them.
