### ISSUE TITLE
PowerCLI sample

### ISSUE THREAD

**Issue by mattmoor** [vmware-tanzu/sources-for-knative#40]
We should make a sample that uses a containerized PowerCLI to script against the API.

[This article](https://blogs.vmware.com/PowerCLI/2013/03/back-to-basics-connecting-to-vcenter-or-a-vsphere-host.html) makes me think we should have our binding setting up the equivalent of: `%APPDATA%\VMware\credstore\vicredentials.xml`

**Comment by mattmoor** [comment]
Looks like this is a containerized PowerCLI image: https://hub.docker.com/r/vmware/powerclicore/

**Comment by mattmoor** [comment]
So I managed to get something relatively simple working using a hacked up version of the govc sample:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: vsphere-script
  labels:
    # Make this Job match the binding!
    role: vsphere-job
spec:
  template:
    metadata:
      labels:
        # So it's easier to list the Pods
        role: vsphere-job        
    spec:
      restartPolicy: Never
      containers:
      - name: create-tag
        image: vmware/powerclicore
        command: ["pwsh", "-Command"]
        args:
        - |
          # Log into the VI Server
          Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null
          Connect-VIServer -Server ([System.Uri]$env:GOVC_URL).Host -User $env:GOVC_USERNAME -Password $env:GOVC_PASSWORD

          # Get Events and write them out.
          Get-VIEvent | Write-Host
```

Right now it needs to explicitly connect with the auth because I haven't found a clever way to have this pulled from the environment.  `Connect-VIServer` seems to support a `-SaveCredentials` option, which hints at a file we could precreate, but this isn't yet supported on PowerCLI Core :(

One thing we could consider doing it mounting our own `Setup-VIBinding.ps1` with a little script that does the above auto-magically.  However, at a minimum I think we should consider cleaning up the environment variables to better align with this use-case, e.g.

```yaml
          # Log into the VI Server
          Set-PowerCLIConfiguration -InvalidCertificateAction $env:VI_CERT_ACTION -Confirm:$false | Out-Null
          Connect-VIServer -Server $env:VI_SERVER -User $env:VI_USERNAME -Password $env:VI_PASSWORD
```

... or something.
